version: '2'

services:
  postgres:
    image: postgres:latest
    container_name: postgresdb
    environment:
      POSTGRES_DB: camper
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/script.sql
    networks:
      - postgres_redis

  redis:
    image: redis:latest
    container_name: redisdb
    ports:
      - "6379:6379"
    networks:
      - postgres_redis

networks:
  postgres_redis:
    driver: bridge