spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/camper
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: